### ISSUE TITLE
Crash on @-moz-document url-prefix()

### ISSUE THREAD

**Issue by timoxley** [reworkcss/rework#71]
Crashes when trying to process `@-moz-document url-prefix()`

``` shell
.../node_modules/rework/node_modules/css/node_modules/css-stringify/index.js:150
    + node.declarations.map(this.declaration, this).join(';\n')
                        ^
TypeError: Cannot call method 'map' of undefined
    at Compiler.rule (/.../node_modules/rework/node_modules/css/node_modules/css-stringify/index.js:150:25)
    at Compiler.visit (/.../node_modules/rework/node_modules/css/node_modules/css-stringify/index.js:43:15)
    at Array.map (native)
    at Compiler.compile (/.../node_modules/rework/node_modules/css/node_modules/css-stringify/index.js:30:32)
    at Object.module.exports [as stringify] (/.../node_modules/rework/node_modules/css/node_modules/css-stringify/index.js:12:32)
    at Rework.toString (/.../node_modules/rework/lib/rework.js:86:14)
    at Object.<anonymous> (/.../rework.js:21:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
make: *** [build] Error 8
```

CSS:

```
@-moz-document url-prefix() {
  .icon-spin {
    height: .9em;
  }
  .btn .icon-spin {
    height: auto;
  }
  .icon-spin.icon-large {
    height: 1.25em;
  }
  .btn .icon-spin.icon-large {
    height: .75em;
  }
}
```

**Comment by Qavai** [comment]
ERROR in ./src/views/*/index.css
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(195:11) postcss-csso: \index.css Selector is expected

  193 |
  194 |                                                                         @-moz-document url-prefix() {
> 195 |                                                                                 & {
      |                                                                                 ^
  196 |                                                                                         white-space: pre-line;
  197 |                                                                                 }

при таком написании так ошибки нет

                                                                        @-moz-document url-prefix() {
                                                                                .kuku {
                                                                                        white-space: pre-line;
                                                                                }
                                                                        }
НО он не развёртывает полные пути до этого элемента в стилях

как это написать?
